package main.classes;
import credits.Ficha; //Hago este import para realizar pruebas de fichas en el cuarto panel temporal
import java.util.List;
import javax.swing.table.DefaultTableModel;





public class Transacciones extends javax.swing.JFrame {

    private String [] tableArray = {"Nombre","Apellido","DNI","Saldo"};
    
     private DefaultTableModel transactionsTableModel;
     
     private DAOClientes daodb = new DAOClientes();
    
    private String[] ArrayFichas = { //esto se usa siquiera? Borrar si no tiene uso alguno
            "Gris",
            "Blanca",
            "Azul",
            "Roja",
            "Verde,",
            "Amarilla",
            "Negra",
            "Naranja",
            "Violeta"        
        };
    
   
    public Transacciones() {
        initComponents();
         setSize(930,630);
         initTable();
         refreshTable();
         clearLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label1_nombre = new javax.swing.JLabel();
        label1_apellido = new javax.swing.JLabel();
        label1_dni = new javax.swing.JLabel();
        label1_saldo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transacciones_jtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        label1_nombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1_nombre.setText("Nombre: ");
        jPanel1.add(label1_nombre);
        label1_nombre.setBounds(20, 10, 180, 30);

        label1_apellido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1_apellido.setText("Apellido:");
        jPanel1.add(label1_apellido);
        label1_apellido.setBounds(20, 50, 180, 30);

        label1_dni.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1_dni.setText("DNI:");
        jPanel1.add(label1_dni);
        label1_dni.setBounds(20, 90, 180, 30);

        label1_saldo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1_saldo.setText("Saldo:");
        jPanel1.add(label1_saldo);
        label1_saldo.setBounds(20, 130, 180, 30);

        panel1.add(jPanel1);
        jPanel1.setBounds(30, 20, 370, 260);

        jTabbedPane1.addTab("Test-Fichas", panel1);

        jPanel2.setLayout(null);
        jTabbedPane1.addTab("Información", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 260, 900, 330);

        jLabel1.setText("Seleccione el usuario correspondiente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 290, 25);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "BD - ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setToolTipText("");
        jPanel3.setVerifyInputWhenFocusTarget(false);
        jPanel3.setLayout(null);

        transacciones_jtable.setAutoCreateRowSorter(true);
        transacciones_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        transacciones_jtable.setToolTipText("");
        transacciones_jtable.setAutoscrolls(false);
        transacciones_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transacciones_jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transacciones_jtable);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 870, 180);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 40, 890, 210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transacciones_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transacciones_jtableMouseClicked
        // TODO add your handling code here:
            if (evt.getClickCount() == 2) {
            int fila = this.transacciones_jtable.getSelectedRow();
            
            String nombre = this.transacciones_jtable.getValueAt(fila, 0).toString();
            String apellido = this.transacciones_jtable.getValueAt(fila, 1).toString();
            String dni = this.transacciones_jtable.getValueAt(fila, 2).toString();
            String saldo = this.transacciones_jtable.getValueAt(fila, 3).toString();
        
            this.label1_nombre.setText("Nombre: " + nombre);
            this.label1_apellido.setText("Apellido: " + apellido);
            this.label1_dni.setText("DNI: " + dni);
            this.label1_saldo.setText("Saldo: " + saldo);
        }
    }//GEN-LAST:event_transacciones_jtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transacciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label1_apellido;
    private javax.swing.JLabel label1_dni;
    private javax.swing.JLabel label1_nombre;
    private javax.swing.JLabel label1_saldo;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable transacciones_jtable;
    // End of variables declaration//GEN-END:variables

    private void initTable(){
        this.transactionsTableModel = new DefaultTableModel(this.tableArray,0){
            
            
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
            
            
         };
        this.transacciones_jtable.setModel(transactionsTableModel);
            
       
    }
    
    private void refreshTable() {
        this.clearTable();
        List<String[]> clientes = daodb.listarTodo();
         for(String[] data: clientes ) {
             this.transactionsTableModel.addRow(data);
         }
             
 }
 
    
     private void clearTable() {
        this.transactionsTableModel.setRowCount(0);
    }
     
     
    private void clearLabels(){
        this.label1_nombre.setText("Nombre: ");
        this.label1_apellido.setText("Apellido: ");
        this.label1_dni.setText("DNI: ");
        this.label1_saldo.setText("Saldo: ");
        
    }
    
    
    
    
    
    
}
    

