package trabajo.casino;

/**
 *
 * @author Facu
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome_lbl = new javax.swing.JLabel();
        clients_menubtn = new javax.swing.JButton();
        lastsession_lbl = new javax.swing.JLabel();
        mainmenubackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_lbl.setBackground(new java.awt.Color(255, 51, 51));
        welcome_lbl.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        welcome_lbl.setForeground(new java.awt.Color(255, 204, 0));
        welcome_lbl.setText("Bienvenido al gestor");
        getContentPane().add(welcome_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, -1));

        clients_menubtn.setBackground(new java.awt.Color(204, 0, 0));
        clients_menubtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clients_menubtn.setForeground(new java.awt.Color(255, 255, 51));
        clients_menubtn.setText("Gestionar Clientes");
        clients_menubtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 153, 0)));
        clients_menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clients_menubtnActionPerformed(evt);
            }
        });
        getContentPane().add(clients_menubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 230, 60));

        lastsession_lbl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastsession_lbl.setForeground(new java.awt.Color(255, 51, 0));
        lastsession_lbl.setText("Último inicio de sesión: ");
        getContentPane().add(lastsession_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 30));

        mainmenubackground.setBackground(new java.awt.Color(255, 102, 0));
        mainmenubackground.setForeground(new java.awt.Color(153, 255, 51));
        mainmenubackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajo/casino/CasinoBackgroundjpg.jpg"))); // NOI18N
        getContentPane().add(mainmenubackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 760, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clients_menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clients_menubtnActionPerformed
        Clientes client = new Clientes();
        client.setVisible(true);
        
    }//GEN-LAST:event_clients_menubtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clients_menubtn;
    private javax.swing.JLabel lastsession_lbl;
    private javax.swing.JLabel mainmenubackground;
    private javax.swing.JLabel welcome_lbl;
    // End of variables declaration//GEN-END:variables
}
